export const UsersDB = [
    {
        _id: "user_1",
        name: "Juan",
        surname: "Gómez",
        dni: "12345678A",
        phone: "123456789",
        email: "juan.gomez@example.com",
        password: "secreta123",
        role: "admin",
        active: true,
        job: "Arquitecto",
        city: "Barcelona",
        image: "https://media.istockphoto.com/id/1331101143/photo/smiling-confident-mature-businessman-looking-at-camera-standing-in-office.jpg?s=612x612&w=0&k=20&c=M6Xv9Zt1RYkKkf0XVuIKpNvhnHgXPX_WWCemPdChfTE="
    },
    {
        _id: "user_2",
        name: "Ana",
        surname: "López",
        dni: "87654321B",
        phone: "987654321",
        email: "ana.lopez@example.com",
        password: "contraseña456",
        role: "admin",
        active: true,
        job: "Arquitecto",
        city: "Madrid",
        image: "https://bostonglobe-prod.cdn.arcpublishing.com/resizer/c_gbJ1MZF_YwD5bKKJ87WQdZudA=/960x0/cloudfront-us-east-1.images.arcpublishing.com/bostonglobe/3QV7OGLAGFBWBA7SE3Y2IJYLQ4.jpg"
    },
    {
        _id: "user_3",
        name: "Miguel",
        surname: "Hernández",
        dni: "45678901C",
        phone: "567890123",
        email: "miguel.hernandez@example.com",
        password: "mypass123",
        role: "operario",
        active: true,
        job: "Delineante",
        city: "Valencia",
        image: "https://img.freepik.com/premium-photo/worker-s-portrait-who-is-building-inspecting-progress-modest-commercial-hall-generative-ai-reliable-civil-engineer-working-construction-site_28914-24730.jpg"
    },
    {
        _id: "user_4",
        name: "Elena",
        surname: "Martínez",
        dni: "89012345D",
        phone: "678901234",
        email: "elena.martinez@example.com",
        password: "password456",
        role: "operario",
        active: true,
        job: "Jefe de Obra",
        city: "Sevilla",
        image: "https://www.shutterstock.com/image-photo/happy-engineer-construction-worker-architect-600nw-2193338333.jpg"
    },
    {
        _id: "user_5",
        name: "Pedro",
        surname: "Sánchez",
        dni: "23456789E",
        phone: "789012345",
        email: "pedro.sanchez@example.com",
        password: "securepass",
        role: "operario",
        active: true,
        job: "Peón",
        city: "Barcelona",
        image: "https://img.freepik.com/premium-photo/worker-s-portrait-who-is-building-inspecting-progress-modest-commercial-hall-generative-ai-reliable-civil-engineer-working-construction-site_28914-24730.jpg"
    },
    {
        _id: "user_6",
        name: "Isabel",
        surname: "Ramírez",
        dni: "67890123F",
        phone: "8901234567",
        email: "isabel.ramirez@example.com",
        password: "pass123",
        role: "operario",
        active: true,
        job: "Peón",
        city: "Madrid",
        image: "https://www.shutterstock.com/image-photo/happy-engineer-construction-worker-architect-600nw-2193338333.jpg"
    },
    {
        _id: "user_7",
        name: "David",
        surname: "García",
        dni: "01234567G",
        phone: "9012345678",
        email: "david.garcia@example.com",
        password: "mypassword",
        role: "operario",
        active: true,
        job: "Peón",
        city: "Valencia",
        image: "https://img.freepik.com/premium-photo/worker-s-portrait-who-is-building-inspecting-progress-modest-commercial-hall-generative-ai-reliable-civil-engineer-working-construction-site_28914-24730.jpg"
    },
    {
        _id: "user_8",
        name: "Laura",
        surname: "Fernández",
        dni: "34567890H",
        phone: "0123456789",
        email: "laura.fernandez@example.com",
        password: "pass456",
        role: "operario",
        active: true,
        job: "Carpintero",
        city: "Sevilla",
        image: "https://www.shutterstock.com/image-photo/happy-engineer-construction-worker-architect-600nw-2193338333.jpg"
    },
    {
        _id: "user_9",
        name: "Carlos",
        surname: "Ortega",
        dni: "78901234I",
        phone: "1234567890",
        email: "carlos.ortega@example.com",
        password: "password789",
        role: "operario",
        active: true,
        job: "Cristalero",
        city: "Barcelona",
        image: "https://img.freepik.com/premium-photo/worker-s-portrait-who-is-building-inspecting-progress-modest-commercial-hall-generative-ai-reliable-civil-engineer-working-construction-site_28914-24730.jpg"
    },
    {
        _id: "user_10",
        name: "María",
        surname: "Luna",
        dni: "12345678J",
        phone: "2345678901",
        email: "maria.luna@example.com",
        password: "mypass789",
        role: "operario",
        active: true,
        job: "Soldador",
        city: "Madrid",
        image: "https://www.shutterstock.com/image-photo/happy-engineer-construction-worker-architect-600nw-2193338333.jpg"
    },
    {
        _id: "user_17",
        name: "Javier",
        surname: "López",
        dni: "32109876G",
        phone: "9012345678",
        email: "javier.lopez@example.com",
        password: "secure123",
        role: "operario",
        active: true,
        job: "Albañil",
        city: "Valencia",
        image: "https://img.freepik.com/premium-photo/worker-s-portrait-who-is-building-inspecting-progress-modest-commercial-hall-generative-ai-reliable-civil-engineer-working-construction-site_28914-24730.jpg"
    },
    {
        _id: "user_18",
        name: "Elena",
        surname: "Pérez",
        dni: "21098765H",
        phone: "0123456789",
        email: "elena.perez@example.com",
        password: "letmein789",
        role: "operario",
        active: true,
        job: "Pintor",
        city: "Madrid",
        image: "https://www.shutterstock.com/image-photo/happy-engineer-construction-worker-architect-600nw-2193338333.jpg"
    },
    {
        _id: "user_19",
        name: "Francisco",
        surname: "Sánchez",
        dni: "10987654I",
        phone: "1234567890",
        email: "francisco.sanchez@example.com",
        password: "mypass123",
        role: "operario",
        active: true,
        job: "Operador de grúa",
        city: "Barcelona",
        image: "https://img.freepik.com/premium-photo/worker-s-portrait-who-is-building-inspecting-progress-modest-commercial-hall-generative-ai-reliable-civil-engineer-working-construction-site_28914-24730.jpg"
    },
    {
        _id: "user_20",
        name: "María",
        surname: "Luna",
        dni: "12345678J",
        phone: "2345678901",
        email: "maria.luna@example.com",
        password: "mypass789",
        role: "operario",
        active: true,
        job: "Operador de grúa",
        city: "Madrid",
        image: "https://www.shutterstock.com/image-photo/happy-engineer-construction-worker-architect-600nw-2193338333.jpg"
    },
];
