export const Users = [
    {
        _id: "1",
        nombre: "Juan",
        apellidos: "Gómez",
        dni: "12345678A",
        telefono: "123456789",
        email: "juan.gomez@example.com",
        contraseña: "secreta123",
        rol: "admin",
        activo: true,
        puesto: "Desarrollador",
    },
    {
        _id: "2",
        nombre: "Ana",
        apellidos: "López",
        dni: "87654321B",
        telefono: "987654321",
        email: "ana.lopez@example.com",
        contraseña: "contraseña456",
        rol: "admin",
        activo: true,
        puesto: "Gerente",
    },
    {
        _id: "3",
        nombre: "Miguel",
        apellidos: "Hernández",
        dni: "45678901C",
        telefono: "567890123",
        email: "miguel.hernandez@example.com",
        contraseña: "mypass123",
        rol: "operario",
        activo: true,
        puesto: "Analista",
    },
    {
        _id: "4",
        nombre: "Elena",
        apellidos: "Martínez",
        dni: "89012345D",
        telefono: "678901234",
        email: "elena.martinez@example.com",
        contraseña: "password456",
        rol: "operario",
        activo: true,
        puesto: "Diseñador",
    },
    {
        _id: "5",
        nombre: "Pedro",
        apellidos: "Sánchez",
        dni: "23456789E",
        telefono: "789012345",
        email: "pedro.sanchez@example.com",
        contraseña: "securepass",
        rol: "operario",
        activo: true,
        puesto: "Ingeniero",
    },
    {
        _id: "6",
        nombre: "Isabel",
        apellidos: "Ramírez",
        dni: "67890123F",
        telefono: "890123456",
        email: "isabel.ramirez@example.com",
        contraseña: "pass123",
        rol: "operario",
        activo: true,
        puesto: "Gerente de Proyecto",
    },
    {
        _id: "7",
        nombre: "David",
        apellidos: "García",
        dni: "01234567G",
        telefono: "901234567",
        email: "david.garcia@example.com",
        contraseña: "mypassword",
        rol: "operario",
        activo: true,
        puesto: "Desarrollador Frontend",
    },
    {
        _id: "8",
        nombre: "Laura",
        apellidos: "Fernández",
        dni: "34567890H",
        telefono: "012345678",
        email: "laura.fernandez@example.com",
        contraseña: "pass456",
        rol: "operario",
        activo: true,
        puesto: "Analista de Datos",
    },
    {
        _id: "9",
        nombre: "Carlos",
        apellidos: "Ortega",
        dni: "78901234I",
        telefono: "1234567890",
        email: "carlos.ortega@example.com",
        contraseña: "password789",
        rol: "operario",
        activo: true,
        puesto: "Tester",
    },
    {
        _id: "10",
        nombre: "María",
        apellidos: "Luna",
        dni: "12345678J",
        telefono: "2345678901",
        email: "maria.luna@example.com",
        contraseña: "mypass789",
        rol: "operario",
        activo: true,
        puesto: "Diseñadora UX",
    }
];
